name: Build

# Run deployment to Github packages on commits to the `main` branch
on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build package
        run: mvn clean package -DskipTests
