on:
  push:
    tags:
      - 'v*-voyager'

name: Create Voyager Release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Extract Semver
        id: semver_parser
        run: |
          semver=${TAG#"refs/tags/v"}
          semver=${semver%"-voyager"}
          echo ::set-output name=semver::$semver
        env:
          TAG: ${{ github.ref }}

      - name: Fill Version
        run: |
          tag=${{ steps.semver_parser.outputs.semver }}
          sed -i "s/\$tag_version/$tag/" gitclient/pom.xml

      - name: Build
        run: mvn clean package

      - name: Prepare Assets
        run: |
          mkdir iglog
          mkdir iglog/results
          cp README.md iglog/README.md
          cp gitclient/target/iglog.jar iglog/iglog.jar
          cp gitclient/src/main/resources/instrument.yml iglog/instrument.yml

      - name: Create Archive
        run: zip -r iglog.zip iglog

      - name: Prepare Release Notes
        run: touch ${{ github.workspace }}/releaseNotes/v${{ steps.semver_parser.outputs.semver }}.md

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Iglog ${{ steps.semver_parser.outputs.semver }} Voyager
          body_path: ${{ github.workspace }}/releaseNotes/v${{ steps.semver_parser.outputs.semver }}.md
          body: ""
          prerelease: false
          draft: false
          fail_on_unmatched_files: true
          files: iglog.zip
